### ISSUE TITLE
License / Terms of Use

### ISSUE THREAD

**Issue by definitelynotrazu** [Aikiro42/Project-45#5]
Wondering what the license and or terms of use are, e.g. I'm interested in making a couple weapons of my own using the very nice reload mechanic you've created, would that be allowed? And could people make addons to the mod? Or fork the mod if development ever stopped one day? etc, etc.

Thanks

**Comment by Aikiro42** [comment]
[GPL-3.0](https://www.gnu.org/licenses/gpl-faq.en.html) added. This requires anyone to credit me AND allow access to the source code in their re/distributions. Even when I stop working on this mod, these requirements and the freedoms of sharing, redistributing as-is/derivatives should hold up.

Hence, you guys _should_ be able to do what you want with my mod as long as you credit me, give access to the sauce code, and (re-)release this under a license that's compatible with GPL-3.0.
